-- Run as an administrator after 01_admin_setup.sql.
-- Expected: exactly three SELECT object grants and no INSERT/UPDATE/DELETE grants.

SET DEFINE OFF

SELECT "GRANTEE", "OWNER", "TABLE_NAME", "PRIVILEGE"
FROM "DBA_TAB_PRIVS"
WHERE "GRANTEE" = 'PLUGIN_TEST_USER'
  AND "OWNER" = 'PLUGIN_TEST_OWNER'
ORDER BY "TABLE_NAME", "PRIVILEGE";

SELECT "GRANTEE", "PRIVILEGE", "ADMIN_OPTION"
FROM "DBA_SYS_PRIVS"
WHERE "GRANTEE" = 'PLUGIN_TEST_USER'
ORDER BY "PRIVILEGE";

SELECT "USERNAME", "ACCOUNT_STATUS"
FROM "DBA_USERS"
WHERE "USERNAME" IN ('PLUGIN_TEST_OWNER', 'PLUGIN_TEST_USER')
ORDER BY "USERNAME";

SELECT "OWNER", "TABLE_NAME", "NUM_ROWS"
FROM "DBA_TABLES"
WHERE "OWNER" = 'PLUGIN_TEST_OWNER'
  AND "TABLE_NAME" IN ('PLUGIN_TEST_USERS', 'PLUGIN_TEST_ORDERS', 'PLUGIN_TEST_LOGS')
ORDER BY "TABLE_NAME";
