-- Run as PLUGIN_TEST_USER. Every statement is read-only.

SET DEFINE OFF

SELECT 1 AS "OK";

SELECT *
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_USERS"
ORDER BY "ID"
LIMIT 5;

SELECT COUNT(*) AS "USER_COUNT"
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_USERS";

SELECT *
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_ORDERS"
WHERE "STATUS" = 'completed'
ORDER BY "ID";

SELECT U."USERNAME", O."PRODUCT_NAME", O."AMOUNT"
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_USERS" U
JOIN "PLUGIN_TEST_OWNER"."PLUGIN_TEST_ORDERS" O ON U."ID" = O."USER_ID"
ORDER BY O."ID"
LIMIT 10;

SELECT "ID", "USERNAME", "EMAIL", "SALARY", "CREATED_AT"
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_USERS"
WHERE "EMAIL" IS NULL OR "SALARY" IS NULL
ORDER BY "ID";

SELECT "ID", "USERNAME"
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_USERS"
WHERE "USERNAME" IN ('Zhang Wei', 'Lea Martin', 'Sun Wukong')
ORDER BY "ID";

SELECT "DEPARTMENT", AVG("SALARY") AS "AVERAGE_SALARY"
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_USERS"
GROUP BY "DEPARTMENT"
ORDER BY "DEPARTMENT";

SELECT "ID", "EVENT_TYPE", "CREATED_AT"
FROM "PLUGIN_TEST_OWNER"."PLUGIN_TEST_LOGS"
WHERE "CREATED_AT" >= TIMESTAMP '2025-02-05 00:00:00'
ORDER BY "CREATED_AT" DESC
LIMIT 5;
